import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/Navbar";
import '@/app/index.css'
import ThemeProvider from "@/components/_app";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      
      <body>
        <ThemeProvider>
          <div className="flex justify-center">   <Navbar/></div>
 
        {children}</ThemeProvider>
   
      </body>
    </html>
  );
}
